#ifndef _EDGE_DEFINES_H_
#define  _EDGE_DEFINES_H_

#define OCALL_PRINT_BUFFER 1
#define OCALL_PRINT_VALUE 2
#define OCALL_SEND_REPORT 3
#define OCALL_WAIT_FOR_REQUEST 4
#define OCALL_SEND_REPLY 5
#define OCALL_WAIT_FOR_CLIENT_PUBKEY 6
/* DEMO CHANGES */
#define OCALL_WAIT_FOR_CLIENT_SESSION_CTX 7
#define OCALL_SAVE_SEALED_DATA 8
#define OCALL_RETRIEVE_SEALED_DATA 9
/* END DEMO CHANGES */
#endif /* _EDGE_DEFINES_H_ */
